collaborate branch
CELYNEBIRUNGI/Portfolio-Project pull request #20
Opened 2023-04-11 12:54 UTC by CELYNEBIRUNGI

Added new Arthur.
Updated the Readme FILE

2023-04-11 14:09 UTC, AbelG101 requested changes
![](https://media.giphy.com/media/ReyD4OdRiHeLDCRaEP/giphy.gif)

# Hi @zbahati 👋, 

You're doing a good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Correct use of GitHub Flow ✔
-  Well-structured files ✔
- All linter checks are passing ✔
- Descriptive PR title with a great summary ✔

## Required Changes ♻️
- _Check the comments under the review._
- You just have to make a few changes and you're on your way 🚀.


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:
- N/A

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-11 14:09 UTC, AbelG101 commented on index.html
- Great job determining changes in your Portfolio 👏 however you need to make some changes to fix the accessibility issues as requested in the project requirement.
    - [x] I noticed that the social media icons in the "home page" and the "about section" don't have `alt` texts kindly make sure that all `img` tags have `alt` attribute with an appropriate alternative text, it is used by people who have visual impairments and use screen readers to hear the alt text read out.
 - [x] As specified in the project requirements please make sure to link to the corresponding line of code ([here's how](http://www.chasewoodford.com/blog/linking-highlighted-lines-code-github/#:~:text=To%20link%20to%20multiple%20lines,php%23L117%2DL148)) where the changes are required in your PR description. 
     ![firefox_Qld0tf4cYR](https://user-images.githubusercontent.com/104968236/231188168-e3028e71-c243-4c39-894d-22e66ec8cc48.png)
- [x] Once again as specified in the project requirements your report should list all points that you have checked you seem to be missing the below checks so please include them:
    - Moving content ❌
    - Multimedia ❌
    - Interaction ❌

2023-04-11 14:58 UTC, AbelG101 requested changes
![](https://media.giphy.com/media/7SyGkO0kQWCfnUC47Y/giphy.gif)


# Hi @CELYNEBIRUNGI & @husush 👋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- Correct use of GitHub Flow ✔
-  Well-structured files ✔
- All linter checks are passing ✔
- Descriptive PR title with a great summary ✔

 ## Required Changes ♻️
- _Check the comments under the review._
- Please go through the comments carefully before requesting a review as I noticed you forgot to implement one of the requirements.

## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-11 14:58 UTC, AbelG101 commented on README.md
- [x] As I requested previously please make sure to link to the corresponding line of code/s in the report where you found some issues in the code. [You can refer to this link for guidance](http://www.chasewoodford.com/blog/linking-highlighted-lines-code-github/#:~:text=To%20link%20to%20multiple%20lines,php%23L117%2DL148).
- [x] This is a [project requirement](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/6_accessability.md) so please make sure you fix it in your next review:

  ![image](https://user-images.githubusercontent.com/104968236/231202580-900a6ef2-718b-4edb-b3e2-fb047c70d8b0.png)

2023-04-11 15:25 UTC, husush23 commented on README.md
https://github.com/CELYNEBIRUNGI/Portfolio-Project/blob/b179aa802035f522bd662df66835274e59d1ca9b/index.html#L29-L33

2023-04-11 16:57 UTC, Shedrack-Sunday requested changes
Hi @CELYNEBIRUNGI            👋 

# CHANGES REQUIRED ♻️

Great work on the project 👏
You've done well implementing the requirements,  However, there are a few you need to work on, to move to the next project. 💯

 
![](https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif)

## Highlights
- Correct use of GitHub Flow ✔
- Well-structured files ✔
- All linter checks are passing ✔
- Descriptive PR title with a great summary ✔
  
# Required Changes ♻️

Check the comments under the review.
You just have to make a few changes based on project requirements, and you're on your way 🚀. 

# Optional suggestions 

Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-04-11 16:57 UTC, Shedrack-Sunday commented on README.md
- [ ] Ass requested by the previous reviewer, please make sure to link to the corresponding line of code/s in the report where you found some issues in the code. You included a snapshot, which does not pass the project requirements. 
-  [ ] You can refer to this [link for guidance](http://www.chasewoodford.com/blog/linking-highlighted-lines-code-github/#:~:text=To%20link%20to%20multiple%20lines,php%23L117%2DL148).

 - This is a [project requirement](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/6_accessability.md) and its needed to get you approved 👍 
 
 ## Instructions 
 
![image](https://user-images.githubusercontent.com/50990925/231234811-ae6b51a5-399e-4e35-ae62-d673065432ce.png)

2023-04-11 17:55 UTC, bimbolabuari commented
Hello @CELYNEBIRUNGI,

Your project already mets all requirements, and your project will be approved manually.

2023-04-12 08:00 UTC, wayungi approved these changes
Hi @CELYNEBIRUNGI , 

![image](https://user-images.githubusercontent.com/99656687/220082459-c1b049c7-5498-42e7-942b-ec7a05d3e603.png)

Great work, your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

**Remember: Every finish line 🏁  is the beginning of a new race 🐎** 

## Highlights
- [ ] All accessibility checks are good ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-12 11:35 UTC, merged